### PR TITLE
Use JLL for library on > 1.3

### PR DESCRIPTION
**Pull request by samuelpowell**

### CODE REVIEW

**Comment by samuelpowell** [comment]
Stalled pending upstream fix https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/672

**Comment by giordano** [comment]
I just realised [registration failed](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=1679&view=logs&j=23ac520b-6243-53c7-e5c0-58fa46006852&t=a36e87de-7c08-5ebb-2706-b0c51721a5a7) :disappointed:   I'm going to rerun it

**Comment by samuelpowell** [comment]
Thanks @giordano yes I only just realised that +1 never made it to BinaryWrappers

**Comment by samuelpowell** [comment]
@ReubenHill can you check okay on Windows?

**Comment by ReubenHill** [comment]
Can't clone and dev or add on windows:

```
(hivedevtest) pkg> add LibFTD2XX#jll
  Updating registry at `C:\Users\Reuben\.julia\registries\General`
┌ Warning: Some registries failed to update:
│     — `C:\Users\Reuben\.julia\registries\General` — registry dirty
└ @ Pkg.Types D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Pkg\src\Types.jl:1199
   Cloning git-repo `https://github.com/Gowerlabs/LibFTD2XX.jl.git`
  Updating git-repo `https://github.com/Gowerlabs/LibFTD2XX.jl.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package libftd2xx_jll [66e46913]:
 libftd2xx_jll [66e46913] log:
 ├─libftd2xx_jll [66e46913] has no known versions!
 └─restricted to versions 1 by LibFTD2XX [85e77ee8] — no versions left
   └─LibFTD2XX [85e77ee8] log:
     ├─possible versions are: 0.3.0 or uninstalled
     └─LibFTD2XX [85e77ee8] is fixed to version 0.3.0
```

**Comment by samuelpowell** [comment]
You have a dirty registry 

``` Warning: Some registries failed to update:
│     — `C:\Users\Reuben\.julia\registries\General` — registry dirty
```

**Comment by samuelpowell** [comment]
Also need to be on >=1.3 (maybe try 1.3.1 to be sure)

**Comment by giordano** [comment]
You probably checked out a branch of the General registry, you may want to go back to master

**Comment by samuelpowell** [comment]
Any luck @ReubenHill ?

**Review by ReubenHill — APPROVED** [review]
All tests pass on windows and I see you've fixed an old mistake I'd made in `FT_DEVICE_LIST_INFO_NODE`. I see you've changed to hard definitions of `DWORD` and `UCHAR`. Has this been tested on ARM?

**Comment by ReubenHill** [comment]
No idea what was wrong with my registry - it had somehow got completely fiddled with

**Comment by samuelpowell** [comment]
Well, just firmed them up to match the tech reference. No tests on ARM but its the same library and it works on Linux so I can't envisage any issues.

**Comment by giordano** [comment]
You can use drone (https://discourse.julialang.org/t/testing-on-arm-with-drone-ci/25871) to test on 32- and 64-bit arm architectures, or Travis for 64-bit arm only (https://discourse.julialang.org/t/julia-aarch64-builds-are-now-available-on-travis-ci/29970)

**Comment by samuelpowell** [comment]
We have Travis for Aarch64, but on _all_ Linux the library doesn't pass tests - its a serial port driver and talks to the kernel so I think it makes CI unhappy.

**Comment by samuelpowell** [comment]
(we have tests which run them there isn't any hardware, but even these want to try and enumerate devices, etc., with knowledge nothing will be found)

**Pull request merged**
